import Head from 'next/head'
import Image from 'next/image'
import Landing from '../Components/Landing'
import Navbar from '../Components/Layouts/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='min-h-screen'>
      <Head>
        <title>Flight App</title>
        <meta name="description" content="Generated by Flight App" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <main className=''>
        <Navbar />
        <Landing />
      </main>

      
    </div>
  )
}
