import Head from 'next/head'

export default function Header() {
  return (
    <Head>
        <title>flightapp</title>
        <meta name="description" content="Generated by create flightapp" />
        <link rel="icon" href="/images/logo.png" />
    </Head>

  )
}
